In [70]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [14]:
df=sns.load_dataset('penguins')
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [19]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [27]:
df.dropna()
df.isnull().sum()


species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [42]:
df_new=pd.DataFrame()
df_new

Empty DataFrame
Columns: []
Index: []

## Feature engineering
- One hot encoding transforming categorical data into numeric

In [52]:
def convert_feature(df,column):
    df_col=pd.get_dummies(column,drop_first=True)
    df_new=pd.concat([df,df_col],axis=1)
    return df_new

df2=convert_feature(df,df['sex'])
df2=convert_feature(df2,df2['island'])
df2


species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  Male  Dream  Torgersen  
0         3750.0    Male     1      0          1  
1         3800.0  Female     0      0          1  
2         3250.0  Female     0      0          1  
4         3450.0  Female     0      0          1  
5         3650.0    Male     1      0          1  
..           ...     ...   ...    ...        ...  
338       4925.0  Female     0      0          0  
340       4850.0  Female     0      0          0  
341       5750.0    Male     1      0          0  
342       5200.0  Female     0      0          0  
343       5400.0    Male     1      0          0  

[333 rows x 10 columns]

In [74]:
Y=df2['species']
Y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
Y

0      0
1      0
2      0
4      0
5      0
      ..
338    2
340    2
341    2
342    2
343    2
Name: species, Length: 333, dtype: int64

In [75]:
X=df2.drop(['species','island','sex'],axis=1)
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Male  \
0              39.1           18.7              181.0       3750.0     1   
1              39.5           17.4              186.0       3800.0     0   
2              40.3           18.0              195.0       3250.0     0   
4              36.7           19.3              193.0       3450.0     0   
5              39.3           20.6              190.0       3650.0     1   
..              ...            ...                ...          ...   ...   
338            47.2           13.7              214.0       4925.0     0   
340            46.8           14.3              215.0       4850.0     0   
341            50.4           15.7              222.0       5750.0     1   
342            45.2           14.8              212.0       5200.0     0   
343            49.9           16.1              213.0       5400.0     1   

     Dream  Torgersen  
0        0          1  
1        0          1  
2        0          1  
4        0          1  
5        0          1  
..     ...        ...  
338      0          0  
340      0          0  
341      0          0  
342      0          0  
343      0          0  

[333 rows x 7 columns]

In [76]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
print('X_train',X_train.shape)
print('X_test',X_test.shape)
print('Y_train',Y_train.shape)
print('Y_test',Y_test.shape)

X_train (233, 7)
X_test (100, 7)
Y_train (233,)
Y_test (100,)


In [77]:
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [78]:
Y_Pred=classifier.predict(X_test)
Y_Pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [79]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score



In [82]:
cm=confusion_matrix(Y_test,Y_Pred)
cm

array([[48,  0,  0],
       [ 1, 15,  0],
       [ 1,  0, 35]], dtype=int64)

In [83]:
accuracy_score(Y_test,Y_Pred)

0.98

In [85]:
print(classification_report(Y_test,Y_Pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.94      0.97        16
           2       1.00      0.97      0.99        36

    accuracy                           0.98       100
   macro avg       0.99      0.97      0.98       100
weighted avg       0.98      0.98      0.98       100



In [100]:
classifier=RandomForestClassifier(n_estimators=8,criterion='gini',random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=8, random_state=0)

In [101]:
Y_Pred=classifier.predict(X_test)
Y_Pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [102]:
cm=confusion_matrix(Y_test,Y_Pred)
cm

array([[48,  0,  0],
       [ 2, 14,  0],
       [ 0,  0, 36]], dtype=int64)

In [103]:
accuracy_score(Y_test,Y_Pred)

0.98

In [104]:
print(classification_report(Y_test,Y_Pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100

